### ISSUE TITLE
MessageSystem does not work without MessageCache because of null

### ISSUE THREAD

**Issue by TureBentzin** [JuliGames/JuliGamesCore#14]

**Comment by TureBentzin** [comment]
```txt
[18:11:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'test' in plugin Test v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.juligames.core.api.jdbi.DBMessage.getMessageKey()" because "dbMessage" is null
        at net.juligames.core.message.CoreMessageApi.cache(CoreMessageApi.java:585) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.lambda$getMessage$1(CoreMessageApi.java:93) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at net.juligames.core.message.CoreMessageApi.getMessage(CoreMessageApi.java:92) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.getMessage(CoreMessageApi.java:29) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBest(CoreMessageApi.java:528) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBestForRecipient(CoreMessageApi.java:524) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:341) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:233) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:29) ~[PaperCore-1.2-20230129.155542-8.jar:?]
        at net.juliusgames.test.commands.TestCmd.onCommand(TestCmd.java:17) ~[test-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
```
