### ISSUE TITLE
CacheAPI is null

### ISSUE THREAD

**Issue by YouTuberPlus** [JuliGames/JuliGamesCore#16]
[21:55:44 ERROR]: [PaperCore] An issue was recorded while trying to load experimental CorePlugins: Cannot invoke "org.bukkit.plugin.Plugin.isEnabled()" because "plugin" is null
[21:55:44 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.isEnabled()" because "plugin" is null
[21:55:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:533)
[21:55:44 WARN]:        at PaperCore-1.2-20230202.153112-9.jar//net.juligames.core.paper.plugin.CorePluginLoadManager.load(CorePluginLoadManager.java:80)
[21:55:44 WARN]:        at PaperCore-1.2-20230202.153112-9.jar//net.juligames.core.paper.PaperCorePlugin.loadCorePlugins(PaperCorePlugin.java:111)
[21:55:44 WARN]:        at PaperCore-1.2-20230202.153112-9.jar//net.juligames.core.paper.PaperCorePlugin.onEnable(PaperCorePlugin.java:75)
[21:55:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:55:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[21:55:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[21:55:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[21:55:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[21:55:44 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[21:55:44 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[21:55:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[21:55:44 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[21:55:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[21:55:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:55:44 ERROR]: [PaperCore] Please be aware that issues regarding this system will have low priority duo to the unclear situation about the future of this system!
[21:55:44 INFO]: [Testtest] Enabling Testtest v1.0-SNAPSHOT
[21:55:44 INFO]: Running delayed init tasks
[21:55:44 INFO]: [Core-1.2] INFO >> [paper-core|Paper@:/api/boot]: Server start finished: running post-start utilities
[21:55:44 INFO]: [Core-1.2] INFO >> [paper-core|Paper@:/api/boot]: Detected plugins depending on core: [Testtest v1.0-SNAPSHOT]
[21:55:44 INFO]: Done (6.848s)! For help, type "help"
[21:55:44 INFO]: Timings Reset
> hallo
[21:55:48 WARN]: Unexpected exception while parsing console command "hallo"
org.bukkit.command.CommandException: Unhandled exception executing command 'hallo' in plugin Testtest v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.benmanes.caffeine.cache.Cache.put(Object, Object)" because the return value of "net.juligames.core.message.CoreMessageApi.getMessageCache()" is null
        at net.juligames.core.message.CoreMessageApi.cache(CoreMessageApi.java:585) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.lambda$getMessage$1(CoreMessageApi.java:93) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at net.juligames.core.message.CoreMessageApi.getMessage(CoreMessageApi.java:92) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.getMessage(CoreMessageApi.java:29) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBest(CoreMessageApi.java:528) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBestForRecipient(CoreMessageApi.java:524) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:341) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:233) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at net.juligames.core.message.CoreMessageApi.sendMessage(CoreMessageApi.java:29) ~[PaperCore-1.2-20230202.153112-9.jar:?]
        at at.christian.test.commands.HalloCommand.onCommand(HalloCommand.java:13) ~[testtest-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more

**Comment by TureBentzin** [comment]
duplicate #14
