### ISSUE TITLE
BStats collection fails at 1.4-SNAPSHOT

### ISSUE THREAD

**Issue by TureBentzin** [JuliGames/JuliGamesCore#25]
```
[18:14:48 WARN]: [PaperCore] Failed to get data for custom chart with id cacheSize
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.concurrent.Callable.call()" is null
        at net.juligames.core.paper.bstats.Metrics$SingleLineChart.getChartData(Metrics.java:468) ~[PaperCore-1.4-SNAPSHOT.jar:?]
        at net.juligames.core.paper.bstats.Metrics$CustomChart.getRequestJsonObject(Metrics.java:433) ~[PaperCore-1.4-SNAPSHOT.jar:?]
        at net.juligames.core.paper.bstats.Metrics$MetricsBase.lambda$submitData$2(Metrics.java:294) ~[PaperCore-1.4-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at net.juligames.core.paper.bstats.Metrics$MetricsBase.submitData(Metrics.java:296) ~[PaperCore-1.4-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>

```

**Comment by TureBentzin** [comment]
This is only a warning and can be ignored for now - it will not affect the cores operation

**Comment by TureBentzin** [comment]
**I investigated this: **

If i understood this the right way, this is intended behavior and this message is only shown, when a especial debug flag for bstats is active.

Because of this, this error should be invisible to the user and only show up if the user wants to see it.

That means, that i can close this issue
