### ISSUE TITLE
Exception with MessageRepresentation

### ISSUE THREAD

**Issue by TureBentzin** [JuliGames/JuliGamesCore#33]
https://github.com/TureBentzin/ConversationLib/issues/1

**Comment by TureBentzin** [comment]
Seems like fixing this resulted in the following exception:
```
[17:56:04 WARN]: Unexpected exception while parsing console command "edit"
org.bukkit.command.CommandException: Unhandled exception executing command 'edit' in plugin MessageEditor v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'replacements' of net/juligames/core/message/CoreMessageApi.insertReplacements must not be null
        at net.juligames.core.message.CoreMessageApi.$$$reportNull$$$0(CoreMessageApi.java) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.insertReplacements(CoreMessageApi.java) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.getMessage(CoreMessageApi.java:112) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBestMessage(CoreMessageApi.java:754) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.findBestMessage(CoreMessageApi.java:731) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.getMessageSmart(CoreMessageApi.java:154) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.message.CoreMessageApi.getMessageSmart(CoreMessageApi.java:143) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.core.adventure.api.MessageRepresentation.represent(MessageRepresentation.java:73) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.messageeditor.messageeditor.EditExecutor$2.getPromptMessage(EditExecutor.java:72) ~[MessageEditor-1.0-SNAPSHOT.jar:?]
        at de.bentzin.conversationlib.Conversation.assemble(Conversation.java:154) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at de.bentzin.conversationlib.Conversation.outputNextPrompt(Conversation.java:137) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at de.bentzin.conversationlib.Conversation.outputNextPrompt(Conversation.java:126) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at de.bentzin.conversationlib.Conversation.begin(Conversation.java:90) ~[PaperCore-1.6-SNAPSHOT.jar:?]
        at net.juligames.messageeditor.messageeditor.EditExecutor.onCommand(EditExecutor.java:117) ~[MessageEditor-1.0-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more

```

**Comment by TureBentzin** [comment]
cant reproduce anymore - might be fixed
